### ISSUE TITLE
Default for public keys should NOT be Private

### ISSUE THREAD

**Issue by mouse07410** [opendnssec/SoftHSMv2#223]
Public keys are created with `CKA_PRIVATE = false` on every hardware token that I know of. This makes sense.

SoftHSMv2 should do the same and drop its insane practice of setting `CKA_PRIVATE = true` by default for *public* keys.

I know you "want to be as restrictive as possible", but there's a line between security and ~~clinical paranoia~~ useless inconvenience that introduces incompatibility with the hardware.

**Comment by rijswijk** [comment]
Mouse wrote:
> Public keys are created with |CKA_PRIVATE = false| on every hardware
> token that I know of. This makes sense.

There are many hardware implementations that default to
CKA_PRIVATE=false, the default for this attribute is independent of the
object type which it is set on. Setting the default to true makes
security sense, because it forces users to think about the objects they
create on a token. Examples of security tokens that set this attribute
to true are IBM HSMs, and, e.g. Sun SCA HSMs, which set it to the same
value as CKA_TOKEN (so if the object is on a token, the default value of
CKA_PRIVATE = true, if it is a session object the default value is false).

> SoftHSMv2 should do the same and drop its insane practice of setting
> |CKA_PRIVATE = true| by default for /public/ keys.

I take offense to the use of the word insane, that is not very
constructive. As explained above, it is a matter of opinion what the
default value is. There is no strong suggestion in the PKCS #11 standard
unfortunately.

As a user of the open source software you are more than welcome to
suggest that this be changed, or submit a pull request. But dictating
changes by claiming the current practice is "insane" does not motivate
us to take it seriously.

> I know you "want to be as restrictive as possible", but there's a line
> between security and clinical paranoia useless inconvenience that
> introduces incompatibility with the hardware.

As explained above, the choice is in line with other implementations.
But it is also a matter of opinion. It does not create an
incompatibility per se, but I do see that it can lead to issues with
software that makes assumptions about the default value and does not set
the value explicitly when creating objects. Unfortunately, PKCS #11 has
many corner cases that software implementers miss and abuse, as someone
who has written PKCS #11 software for years I can tell you from
experience that is impossible to create an implementation that will work
out of the box with all software that uses PKCS #11 to interface with
security tokens.

If you have specific software that you would like to have interoperate
with SoftHSM v2, that does not work because of this particular
implementation choice please let us know so we can consider changing the
default.

Best regards,

Roland

-- 
-- Roland M. van Rijswijk - Deij
-- SURFnet bv
-- w: http://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl

**Comment by mouse07410** [comment]
> I take offense to the use of the word insane, that is not very constructive. 

OK, granted.

> As explained above, it is a matter of opinion what the default value is. There is no strong suggestion in the PKCS#11 standard unfortunately.

In http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959715 section 4.4 table 16 says that CKA_PRIVATE should be true if the object is a private object - the logic of PKC suggests that public keys are called public for a reason. Comments to table 25 suggest that this attribute is related to CKA_ALWAYS_AUTHENTICATE attribute that is one of the *private* key attributes. 

So while you may say there is no *strong* suggestion, it certainly seems to lean towards what seems obvious: private key should not be accessed without authentication and it should never leave the token, while the public key should be exportable and available to the public, as usually is the case.

> If you have specific software that you would like to have interoperate with SoftHSM v2, that does not work because of this particular implementation choice please let us know so we can consider changing the default.

Older versions of OpenSC tools (`pkcs11-tool` in particular) did not explicitly set this attribute, so on (at least some) LTS-level (and legacy) systems this would be a problem. Unfortunately I work with some of such systems. (I also work with the current Github master of OpenSC that does not have this deficiency.)

Overall, I hope you would agree that the default for private and symmetric keys should be "private" (stay on the token, accessible with PIN only), and the default for public keys and certificates should be "public" (which among other things allows access to public keys without having to prompt the user for his PIN - a bonus for hands-off scripts and operations, which my scripts use extensively).

**Comment by rijswijk** [comment]
>     As explained above, it is a matter of opinion what the default value
>     is. There is no strong suggestion in the PKCS#11 standard unfortunately.
> 
> In
> http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959715
> section 4.4 table 16 says that CKA_PRIVATE should be true if the object
> is a private object - the logic of PKC suggests that public keys are
> called public for a reason. Comments to table 25 suggest that this
> attribute is related to CKA_ALWAYS_AUTHENTICATE attribute that is one of
> the /private/ key attributes.
> 
> So while you may say there is no /strong/ suggestion, it certainly seems
> to lean towards what seems obvious: private key should not be accessed
> without authentication and it should never leave the token, while the
> public key should be exportable and available to the public, as usually
> is the case.

This is a new suggestion in PKCS #11 v2.40 that was not present in
earlier versions of the standard AFAIK. I agree that while it's not a
strong suggestion, at least is a constructive hint ;-)

>     If you have specific software that you would like to have
>     interoperate with SoftHSM v2, that does not work because of this
>     particular implementation choice please let us know so we can
>     consider changing the default.
> 
> Older versions of OpenSC tools (|pkcs11-tool| in particular) did not
> explicitly set this attribute, so on (at least some) LTS-level (and
> legacy) systems this would be a problem. Unfortunately I work with some
> of such systems. (I also work with the current Github master of OpenSC
> that does not have this deficiency.)
> 
> Overall, I hope you would agree that the default for private and
> symmetric keys should be "private" (stay on the token, accessible with
> PIN only), and the default for public keys and certificates should be
> "public" (which among other things allows access to public keys without
> having to prompt the user for his PIN - a bonus for hands-off scripts
> and operations, which my scripts use extensively).

OK, clear. There is an open pull request for this feature, I leave it up
to our main developer, @bellgrim to take the final decision on
integrating it or not. My advice would in this case be to do so, but to
also make this change explicit in the documentation, as it is a
deviation from the "old" behaviour of SoftHSM v2.

Cheers,

Roland

-- 
-- Roland M. van Rijswijk - Deij
-- SURFnet bv
-- w: http://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl

**Comment by mouse07410** [comment]
I concur. Also, in `pkcs11-cka-public-key-info-r4-2.docx` it does not include CKA_PRIVATE in the list of the "common" public key attributes. In the list of the common *private* key attributes it includes CKA_ALWAYS_AUTHENTICATE, and links it to CKA_PRIVATE (similar to what I mentioned in my previous post). 

My personal opinion is - it's so obvious that they did not even think about crossing this tee, and state explicitly that "oh yes, do not mark a public key private". But I don't think I have stronger evidence than above.

**Comment by bellgrim** [comment]
I agree to change the default value to CKA_PRIVATE=false for public keys according to the discussion above.

The history behind setting it to true by default was that PKCS#11 v2.20 provided no default value (just said it was token-specific) and that we generally used the most strict option / value when we had to make our own choice. OpenDNSSEC was the primary application using SoftHSM, which always authenticate to the HSM. It was thus no problem that the public key was set to CKA_PRIVATE=true.

The changed behaviour will be documented in the release notes.

**Comment by mouse07410** [comment]
Thank you!
