### ISSUE TITLE
Support linking static runtime in windows

### ISSUE THREAD

**Issue by matthauck** [opendnssec/SoftHSMv2#226]
Currently the Configure.py script generates VS solution/project files that have no runtime library configured, which defaults to dynamically linking the runtime library ("/MD"), but we need to build it with a static runtime ("/MT"). Would you be able to expose this as a config option? Or perhaps just provide some kind of `CFLAGS`-ish mechanism to pass extra compile flags?

**Comment by bellgrim** [comment]
Fixed in #363 

You also need to modify the build configuration for CppUnit if you want to compile the SoftHSM tests. Change "Runtime Library" to "Multi-threaded (/MT)" in the project "cppunit". This will create some build errors for project "TestRunner", but that can be ignored since it is not used by SoftHSM.

Add option enable-static-runtime to the SoftHSM configuration if you want to compile with static CRT (/MT)
