### ISSUE TITLE
RSA key-import sets CKA_ENCRYPT and CKA_DECRYPT statically

### ISSUE THREAD

**Issue by mdomke** [opendnssec/SoftHSMv2#257]
When I import a key-pair using the `softhsm2-util` that I previously generated with openssl, I can  neither use the public key for encryption nor the private key for decryption. This is because the importer sets the corresponding attributes (`CKA_ENCRYPT`/`CKA_DECRYPT`)  statically to `CK_FALSE`. See: https://github.com/opendnssec/SoftHSMv2/blob/c4ef48dadc1ee81b50fdebf1d2a9517047352adf/src/bin/util/softhsm2-util-ossl.cpp#L241
Is there any specific reason for it or could this considered to be a bug?

**Comment by bellgrim** [comment]
The attribute template is a legacy from when it was made to match the template used in libhsm for OpenDNSSEC. Back then, only signing and verifying could be done.

Since we now support more operations, maybe we should set both encrypt/decrypt and wrap/unwrap to true?

You can change the attribute by calling C_SetAttributeValue().

**Comment by mdomke** [comment]
I guess so… Should I create a pull request for it?

**Comment by bellgrim** [comment]
That would be great!

**Comment by mdomke** [comment]
See #259
