### ISSUE TITLE
Problem with initializing more than one token in softhsm2

### ISSUE THREAD

**Issue by ghost** [opendnssec/SoftHSMv2#446]
I am new to softhsm2.

Initially we were creating once session per thread for cryptographic operation.Sessions were created using only one token.But we could not see much increase in performance of using multi threading. So we decided  to use different tokens and session linked to those different session to increase performance. But I could not find a way to initialize more than one token without calling C_Finalize() .When one thread calls C_Finalize() while the other thread is performing cryptographic operation , the application crashed . Is there a way by which we could initialize more than one tokens without calling C_Finalize().

I had another question in mind.My understanding from using softhsm2-util was one slot can have only one tokens. But the diagram provided in https://wiki.opendnssec.org/display/SoftHSMDOCS/High+level+overview+of+SoftHSM+v1+key+storage shows there can be more than one tokens in a slot.Please clarify my doubt in this matter

**Comment by rijswijk** [comment]
OK, so, you can only have a single token per slot, not multiple. If you want to improve performance, using multiple tokens is an option but do note that SoftHSM was designed for security rather than speed. Concretely, this means that key material is generally stored in encrypted form, and only decrypted just-in-time for use, which obviously impacts performance. If you want to optimise for speed alone, you may want to look at directly using a crypto library such as OpenSSL. If, on the other hand, you want to go for a solution that is as secure as possible in software, then SoftHSM is a good option.

Hope this helps.

**Comment by garg-abhishek** [comment]
So @rijswijk let me put this in points.Please correct me if i am wrong.

1.There can be only one token per slot . So the diagram provided in https://wiki.opendnssec.org/display/SoftHSMDOCS/High+level+overview+of+SoftHSM+v1+key+storage is wrong.

2.Even multi threading was not able to show much increased performance because softHSM was designed for security.Using crypto library such as OpenSSL may increase performance but may not be as secure as softhsm.

But there are still some doubt.
1. If i use multiple tokens , will it impact security at any point.

2. Multi threading was not showing much increased performance. Is that only because i was using single token.

3 . Can we initialize more than one tokens without calling C_Finalize(). Or is there any method by which i can initialize a new token at any point of time when the application is running.

4. If we cannot initialize more than one tokens at any point of time when the application is running , we can initialize some tokens before

**Comment by garg-abhishek** [comment]
So @rijswijk let me put this in points.Please correct me if i am wrong.

1.There can be only one token per slot . So the diagram provided in https://wiki.opendnssec.org/display/SoftHSMDOCS/High+level+overview+of+SoftHSM+v1+key+storage is wrong.

2.Even multi threading was not able to show much increased performance because softHSM was designed for security.Using crypto library such as OpenSSL may increase performance but may not be as secure as softhsm.

But there are still some doubt.
1. If I use multiple tokens , will it impact security at any point.

2. Multi threading was not showing much increased performance. Is that only because i was using single token.

3 . Can we initialize more than one tokens without calling C_Finalize(). Or is there any method by which i can initialize a new token at any point of time when the application is running.

4. If we cannot initialize more than one tokens at any point of time when the application is running , we can initialize some tokens at the beginning of the application and can create some kind of thread pool. Will this design improve performance ?

**Comment by rijswijk** [comment]
> So @rijswijk let me put this in points.Please correct me if i am wrong.
> 
> 1.There can be only one token per slot . So the diagram provided in https://wiki.opendnssec.org/display/SoftHSMDOCS/High+level+overview+of+SoftHSM+v1+key+storage is wrong.

That diagram applies to the previous major version of SoftHSM (v1), which has long been deprecated. If you want to know more about the design of SoftHSM v2, you can find this here:

https://wiki.opendnssec.org/display/SoftHSM/v2+Design

> 2.Even multi threading was not able to show much increased performance because softHSM was designed for security.Using crypto library such as OpenSSL may increase performance but may not be as secure as softhsm.
> 
> But there are still some doubts :
> 
> 1. If I use multiple tokens , will it impact security at any point.

No, it will be secure regardless of the number of tokens you use. Adding more tokens will likely make your solution more complex to manage though.

> 2. Multi threading was not showing much increased performance. Is that only because i was using single token.

Possibly; there are critical sections in the code that can only be entered if a mutex has been acquired which may also throttle multi-threaded performance on a single token. You can, of course, always experiment with multiple tokens.

> 3 . Can we initialize more than one tokens without calling C_Finalize(). Or is there any method by which we can initialize a new token at any point of time when the application is running.

I think you misinterpret what C_Initialize/C_Finalize does; you should only call C_Initialize exactly once when initialising use of the PKCS #11 library, and you should only invoke C_Finalize exactly once when you are done using the library (typically when your application shuts down). Please refer to the PKCS #11 standard, which is available for free from Oasis, for more information.

> 1. If we cannot initialize more than one tokens at any point of time when the application is running , we can initialize some tokens at the beginning of the application and can create some kind of thread pool. Will this design improve performance ?

I don't know. You can easily initialize additional tokens on the fly while the application is running, but once a token has been created, it cannot trivially be destroyed from within the application.
