### ISSUE TITLE
Concurrent operations

### ISSUE THREAD

**Issue by jahluwalia** [opendnssec/SoftHSMv2#447]
Hi, 

We're doing some load testing on our software. How many concurrent sessions to a slot does softhsm support? How many concurrent operations or sessions does it support? Is there a max number of objects that we could be hitting?

We're seeing some issues where we start seeing "unable to find base key" or "unable to find wrapping key", when we throw 30-50 concurrent sessions. 

Thanks,
Jas

**Comment by rijswijk** [comment]
There are no hard limits on the number of concurrent operations or sessions in SoftHSM; the number of objects is in principle only limited by the number of files or storage space (whichever runs out first) on the filesystem. It is possible that under heavy load you will hit some limits imposed on the user by the shell (e.g. maximum number of open file descriptors), which may lead to unexpected behaviour.

The messages you report seeing are likely not being thrown by SoftHSM, since those messages are not present in the SoftHSM code base. You may want to turn on debug logging in SoftHSM to check what is happening internally.

Note though, that SoftHSM was designed for security rather than speed, so is likely not the best choice for performance testing of an application.
