### ISSUE TITLE
Performance of C_GenerateRandom with parallel threads

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#458]
As part of my ongoing project to develop a testing harness for PKCS#11 devices I have integrated into it TESTU01. Of those that aware of TESTU01 will know that the crush and big crush tests take a long time to perform. So that a test takes hours rather than days I have produced a parallel threaded version of TESTU01 (based on some previous work (see https://github.com/rski/testu01-parallel for details).  I had hoped that when using 4 threads on a 4 core PC I would see a considerable improvement. However, the performance degraded significantly. 
At this point I wasn't too sure whether this was due to TESTU01, softhsmv2/openssl - or the way I was using openmp to support the multi-threading. To narrow it down I created a standalone program which did two tests.  (1) looping around many times in "n" parallel threads with each thread doing some simple arithmetic and recording the time to execute. (2) as for 1 - but each each thread I would open up a separate session and the loop around calling C_GenerateRandom to obtain 4 bytes of random data - and the record the time to execute. Hence on the (2) test I would have separate sessions for each of the threads. Both the tests used the same openmp constructs.

I then ran the tests with 1,2,3,4, 6 and 8 threads.

Test 1 gave exactly the results I would have expected of a 4 core i7 (with each core supporting 2 hyper threads.  However, test 2 showed significantly degradation above 3 threads.

![RNG_loop](https://user-images.githubusercontent.com/37559949/54352180-eda34280-4648-11e9-945b-bef42c9f754d.png)
![simple_loop](https://user-images.githubusercontent.com/37559949/54352184-f136c980-4648-11e9-8608-0129dc6876b4.png)
I have attached two figures that plot the time to take to execute the tests compared to the number of threads.

It would seem to me that perhaps there is something locking some of the code in either softhsmv2 or openssl that prevents many parallel threads from obtaining random numbers in an efficient manner.

I'm using openssl 1.1.1a and a develop version of softhsmv2 which I downloaded only a few weeks ago

John

**Comment by rijswijk** [comment]
There are three issues in play here:

1) there may indeed be locking that limits how parallelisable random number generation is
2) if the random number generator runs out of entropy, this may also impact performance (compare to using /dev/urandom vs. /dev/random), although I'm not sure what will happen under the hood with this version of OpenSSL
3) it is likely that the random number generation requires system calls, which then requires a kernel page table switch due to Spectre mitigations in the kernel; you can turn this off on the Linux kernel commandline by specifying the flag "nopti". Alternatively, asking for more random bytes probably reduces the number of system calls required.

To be honest though, at the moment we do not have sufficient resources to address this performance bottleneck. So while we appreciate your feedback, I would like to caution that it is unlikely that this will be picked up for development any time soon.

**Comment by johughes99** [comment]
That's no problem.  I just wanted people to be aware of the issue - for the record!
