### ISSUE TITLE
Curve 25519 and Edwards 448 - CKR_GENERAL_ERROR

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#468]
In my test harness I try and enumerate what elliptic curves a given token supports.  The way I do this is my trying to to generate a key pair using C_GenerateKeyPair with the specified OID of the algorithm. This works fine for a collection of NIST, Certicom and brainpool curves.

But then I try and do the same for 25519 and Ed448 - using "old" and "new" oid values.  The error response I get is CKR_GENERAL_ERROR. If they were not supported I would thought it should have reported back CKR_CURVE_NOT_SUPPORTED?

Ive build SOftHSMv2 with openssl 1.1.1a.  When I entered the command:

   openssl ecparam -list-curves

I can see all the curves supported - although 25519 and ed448 aren't listed - although I understand they are supported when used directly with DH.

**Comment by rijswijk** [comment]
If you look in ```SoftHSM.cpp``` from line 5782, you can see that in v2.5.0 at least SoftHSM should return ```CKR_MECHANISM_INVALID``` for ```CKM_EC_EDWARDS_KEY_PAIR_GEN``` if it is not supported. What I suspect may be happening is that you try to use the normal, supported key generation mechanism with an OID that OpenSSL doesn't recognise and that the ```CKR_GENERAL_ERROR``` is returned in the ```generateEC``` function from line 8639 onward. You could confirm this by turning on logging and look for the following message:

```
Could not generate key pair
```

Due to the way the EC key handling is built up, it is not trivial to change the behaviour to return ```CKR_CURVE_NOT_SUPPORTED```, and ```CKR_GENERAL_ERROR``` is an acceptable catch-all that basically says "something is wrong". In case you were indeed trying to generate Edwards keys with the normal EC mechanism then this would not be an unexpected response ;-)

**Comment by johughes99** [comment]
Just looked at syslog and indeed there is an error:

  SoftHSM.cpp(8696): Could not generate key pair

I used the standard C_GenerateKeyPair with OIDs specified in the RFC.

I must admit I was not aware of CKM_EC_EDWARDS_KEY_PAIR_GEN. Have you a list of these "no-standard" mechanisms supported by SoftHSMv2 and documentation on what the calling parameters are?

**Comment by rijswijk** [comment]
No, the vendor defined mechanism is a temporary place holder until the specification catches up and incorporates a mechanism for Edwards curves, but the fact that this does require a vendor-defined mechanism is specified in the release notes (```NEWS``` in the tarball).
