### ISSUE TITLE
The RSA PrivateKey stored in SoftHSM becomes unextractble

### ISSUE THREAD

**Issue by meishijia** [opendnssec/SoftHSMv2#484]
I generate a pair of RSA public/private key with one certain Provider(not softHSM).  Then I use the softHSM as keystore and store the RSA private key in it. When I access the key I stored before, the private key becomes unextractale. I cannot use it in JVM  to create a PrivateKey object and use it to sign.
So I wonder, if there is any way to modify the attribute of the the private key object in softHSM, then I can get the real secret material. 
Thanks a lot!

**Comment by rijswijk** [comment]
If you want to make a key extractable, you need to set the ```CKA_EXTRACTABLE``` attribute to ```CK_TRUE``` when creating the object, as the default value for this attribute for private keys is ```CK_FALSE```. Depending on what you are trying to achieve, however, you may want to check in the Java documentation whether you actually need to extract the key, because in order to sign data or decrypt it, Java should be able to do that through PKCS #11 calls without needing to extract the key.

**Comment by meishijia** [comment]
Thank you very much for answering my question :)


 
---Original---
