### ISSUE TITLE
Windows x64 development branch compilation only works with OpenSSL 1.1.1c

### ISSUE THREAD

**Issue by koh-osug** [opendnssec/SoftHSMv2#495]
I'm using VS 2017. I also tried VS 2015.

* for OpenSSL 1.0.2s I got the error: "__iob_func": undefined external symbol and 3 other undefined symbols.
* for OpenSSL 1.1.0k I got the error: "NID_ED25519": undefined symbol

The  `WIN32-NOTES.md` is only referring to version 1.1.0a and version 1.0.2.d. I would assume compatible versions are also working. The  `WIN32-NOTES.md` needs an update to support only the 1.1.1 series or all listed versions have to be supported.

**Comment by rijswijk** [comment]
We do not exhaustively test all versions of OpenSSL on Windows, we currently test builds with OpenSSL 1.0.2j and 1.1.0b using AppVeyor. Those builds pass. The errors you are reporting sound like build issue with OpenSSL rather than SoftHSM, the second error looks like you're trying to build with EdDSA support whereas the required symbol for that is not present in the OpenSSL build.

**Comment by halderen** [comment]
Of course we can't test with all versions.  We've now switched to vcpkg meaning that we test against what is the current package available there, and the build succeeded for the 2.6.0 run.
