### ISSUE TITLE
Using vendor defined mechanism on softhsm

### ISSUE THREAD

**Issue by onesick** [opendnssec/SoftHSMv2#533]
Hi there,

We are using Luna6 HSM, and for our C_derive_key operation, we are using vendor defined mechanism:
CKM_DES2_DUKPT_DATA                  = 0x80000614
Because these are not defined in softhsm, my unit test fails. Is there a command? Or how can I add this specific mechanism added to the softhsm?
I also wonder if the softhsm will be able to calculate with the above parameter.
Can you please advice, in general, how would I be able to test vendor defined mechanisms in unit tests using softhsm?

Thank you.

**Comment by rijswijk** [comment]
The (Safenet) Luna 6 HSM is a commercial product outside of our control. Vendor-defined mechanisms are precisely that, vendor specific, so I'm afraid we cannot help you very much with this. I don't know what the mechanism does, but you can, of course, build your own implementation into SoftHSM. Unfortunately, our project is run entirely by volunteers at the moment, so I cannot offer you much more than suggesting that you try and implement this yourself if you really need it.

**Comment by onesick** [comment]
I am willing to implement it and make a PR. 
Since I have limited exposure in cryptography, I do not know where I need to code.
I have been gathering information about creating a vendor defined mechanism. 
I found a commit where potentially I could reference to: https://github.com/opendnssec/SoftHSMv2/commit/ba7c7ef783ea7171ff8adbc94a71f0953b37b938
What I cannot measure is how much change I would need to make for a simple vendor mech implementation. Do I have to modify all these files? 
Basically, I need to use C_DeriveKey function, and send this specific mechanism. This mech is defined is CKM_VENDOR_DEFINED + 0x614. It uses the same regular param CK_KEY_DERIVATION_STRING_DATA, and takes key type of CKK_DES2. It looks like it's using the same underlying algorithm that's being used in CKM_DES3_ECB_ENCRYPT_DATA. 
Can I even make this change? https://github.com/opendnssec/SoftHSMv2/blob/f82d4eda55401a4d23e647d85a00a8b0c8ccf712/src/lib/pkcs11/pkcs11t.h
file does not exist anymore either...

**Comment by rijswijk** [comment]
So it should be simpler than the commit you are referring to, because you're not actually implementing a new cryptographic algorithm, but rather are adding a new feature for an existing algorithm. While we appreciate your offer of sending a PR, I don't think we would merge non-standard functionality into the code base (a vendor-defined mechanism is considered non-standard). If you want to do this really correctly, the vendor-defined mechanism should be specified outside the main PKCS #11 headers and should live in its own header. The reason for this is that any application that uses PKCS #11 will normally have been compiled against the standard headers anyway (so doesn't know of the mechanisms), and only special applications that use the mechanism will use the specific header for this purpose. I don't know how Safenet did this for the Luna PKCS #11 library, but I wouldn't be surprised if it requires an extra header file to get this mechanism.

**Comment by onesick** [comment]
Hi @rijswijk 
I made code changes, and re-compiled code by running make command. I also re-installed libraries by running make install, although not sure if it matters.
I have not changed the any other stuff from my previous installed softhsmV2. Do I need to re-start the softhsm somehow to use the newly compiled code? I could not find any development instruction. So I hope you can help.

Thanks!

**Comment by rijswijk** [comment]
It's hard for me to judge how your system is set up and which library it loads; from what I can see in the commits you have, you are not announcing this mechanism to the outside world in the list of supported mechanisms, which you would need to do in ```SoftHSM.cpp``` in the ```prepareSupportedMechanisms``` function (see [here](https://github.com/opendnssec/SoftHSMv2/blob/924cba83a0fbbbddde53ad59b4f1c28752a47303/src/lib/SoftHSM.cpp#L683)).
