### ISSUE TITLE
delete stale slot

### ISSUE THREAD

**Issue by celesteking** [opendnssec/SoftHSMv2#554]
There should be something done with stale slot. Stupid strongswan stumbles upon it and errors out because it's not initalized. I want to be able to erase it so that pkcs11 no longer knows about it.

```
# softhsm2-util --show-slots
Available slots:
Slot 1388482162
    Slot info:
        Description:      SoftHSM slot ID 0x52c28e72                                      
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.6
        Firmware version: 2.6
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.6
        Firmware version: 2.6
        Serial number:    058d033952c28e72
        Initialized:      yes
        User PIN init.:   yes
        Label:            SW token 1                      
Slot 1
    Slot info:
        Description:      SoftHSM slot ID 0x1                                             
        Manufacturer ID:  SoftHSM project                 
        Hardware version: 2.6
        Firmware version: 2.6
        Token present:    yes
    Token info:
        Manufacturer ID:  SoftHSM project                 
        Model:            SoftHSM v2      
        Hardware version: 2.6
        Firmware version: 2.6
        Serial number:                    
        Initialized:      no
        User PIN init.:   no
        Label:     
# softhsm2-util --slot 1 --delete-token
ERROR: A token must be supplied. Use --serial <serial> or --token <label>
# softhsm2-util  --delete-token --token  ''
ERROR: Could not find a token using --serial or --token.
```

Thanks.

**Comment by rijswijk** [comment]
The uninitialised empty slot is there so you can add additional tokens to SoftHSM. There is always one slot with an uninitialised token in it. The software you are using should ignore uninitialised tokens per the PKCS #11 specification, I suggest you open an issue with them, because the application is not following the spec. Any PKCS #11 library may have uninitialised tokens (e.g. a smart card PKCS #11 is likely to have this too if a new card is inserted).

If you really want this behaviour to be different in SoftHSM, you could considering adding configurable functionality for that purpose.

**Comment by celesteking** [comment]
This should really be configurable, but ok. (have opened a bugreport with them)

**Comment by rijswijk** [comment]
We would welcome a pull request, but don't have the time to implement this feature currently, we are an entirely volunteer-run project.

**Comment by Aearsis** [comment]
We use a custom patched version where the total number of slots is configurable (while keeping the curent behavior when set to zero). Shall I submit that as a PR?
