### ISSUE TITLE
Changing  CKA_WRAP_WITH_TRUSTED

### ISSUE THREAD

**Issue by johughes99** [opendnssec/SoftHSMv2#584]
I have a test where I attempt to change the value of the  CKA_WRAP_WITH_TRUSTED attribute in a secret key from FALSE to TRUE.  

it fails with CKR_ATTRIBUTE_READ_ONLY

But reading the base spec and looking at table 27 CKA_WRAP_WITH_TRUSTED  is marked with note 11 from table 10.

And this says "Attribute cannot be changed once set to CK_TRUE. It becomes a read only attribute".

I have checked - and CKA_MODIFIABLE is set to TRUE

So - am I missing something why SoftHMSv2 is returning CKR_ATTRIBUTE_READ_ONLY?

**Comment by rijswijk** [comment]
I checked the code for you, the implementation enforces the correct behaviour (see [`P11Attributes.cpp` at line 1839](https://github.com/opendnssec/SoftHSMv2/blob/e32ed84a92178256b8b3c617bd69004ac303d796/src/lib/P11Attributes.cpp#L1839)). If the attribute does not exist, `false` is assumed as default value in the call, otherwise whatever value the attribute is set to is interpreted. So AFAICS, if the check on that attribute leads to `CKR_ATTRIBUTE_READ_ONLY`, that implies that attribute has to be set to `CK_TRUE`. Perhaps adding a debug log statement here can help (to check if this is the point int the code that gives this return value)?

**Comment by johughes99** [comment]
Unless I'm missing something  shouldn't:


		if (osobject->getBooleanValue(CKA_WRAP_WITH_TRUSTED, false))
		{
			return CKR_ATTRIBUTE_READ_ONLY;
		}

read

		if (osobject->getBooleanValue(CKA_WRAP_WITH_TRUSTED, true))
		{
			return CKR_ATTRIBUTE_READ_ONLY;
		}

**Comment by rijswijk** [comment]
No, the code is correct, the default value of the attribute according to the spec is `CK_FALSE`. The second argument of the function call is the value that is returned if the attribute does not exist on the object (i.e. the default value). Therefore, if the attribute does not exist and false is returned, the `if` evaluates to `false` (and thus the code below will be executed, rather than returning `CKR_ATTRIBUTE_READ_ONLY`).

**Comment by johughes99** [comment]
OK.  WIll dig further and put in some debug points.

However just download latest source and getting the below

`softhsm2-util --show slots
softhsm2-util: SlotManager.cpp:82: void SlotManager::insertToken(ObjectStore*, CK_SLOT_ID, ObjectStoreToken*): Assertion `result.second' failed.
Aborted (core `dumped)`

**Comment by rijswijk** [comment]
That does not look familiar. When you say latest source, do you refer to a tarball of 2.6.1 or is this the current state of the development branch? (the latter contains a number of fixes compared to the 2.6.1 tarball that are worth including).

**Comment by johughes99** [comment]
Latest source from dev branch

**Comment by rijswijk** [comment]
It's kind of hard to help you with that, I just did a fresh build and check, and that call works fine for me :-/

**Comment by johughes99** [comment]
Not just why - but I cleared it by deleting all the tokens I had in /var/lib/softhsm/tokens

Now it works  Back to looking at the issue at hand

**Comment by johughes99** [comment]
Digging through the code as much as I can understand

The CKR_ATTRIBUTE_READ_ONLY is return from the function 

`CK_RV P11Attribute::update(Token* token, bool isPrivate, CK_VOID_PTR pValue, CK_ULONG ulValueLen, int `op)'`

It returns this value because it falls through to the bottom of the function. I can see it goes through - as appropriate - certain Table 10 checks.  But what I dont see is any logic for ck11 - ie  note 11 from table 10  which says "Attribute cannot be changed once set to CK_TRUE. It becomes a read only attribute".

There are actually only 2 attributes with note 11 assigned to them to table 10 CKA_WRAP_WITH_TRUSTED and CKA_SENSITIVE.

So should P11Attribute::update have some logic like the following in it

`	if ((checks & ck11) == ck11)
	{
		if (OBJECT_OP_SET==op)
		{
			return updateAttr(token, isPrivate, pValue, ulValueLen, op);
		}
	}
 `
I did a quick prototype of the code - and it does seem to do what is required

**Comment by rijswijk** [comment]
Should be fixed when #591 is merged, @johughes99 if you want to test, clone a fresh copy of the repository and switch to branche `fix_issue_584`.

**Comment by johughes99** [comment]
Yes - that fixes it.  

I will go on and check #585 as well later today
