### ISSUE TITLE
non-deterministic order of objects returned from PKCS11 C_FindObjects

### ISSUE THREAD

**Issue by Jakuje** [opendnssec/SoftHSMv2#610]
If I see, right, at this moment, objects returned from FindObjects in PKCS#11 are ordered by the handle, because they come through a `std::set`, which sorts them before returning. This is not a problem in most of the cases where we either know what objects we are searching for or when the order really does not matter as the output is just printed or something like this.

This becomes an issue in applications, which do not provide a way for reasonable filtering and try to use all objects and there are more than one of a type (pubky, cert, ...), for example OpenSSH, which attempts all of them for authentication. The solution is to provide deterministic ordering of the keys, for example based on their `CKA_ID`s (if there are duplicates, order according to the unique handle). Similarly, we have this issue in `libcacard`, which shares all the objects from PKCS#11 to the VM. Normal PKCS#11 modules with real smart cards have the keys generally in order of authentication, signature, encryption and if softhsm returns the keys in no particular order, it is easy to mix them up.

At this moment, I do not have any code ready to submit, but I would like to hear your opinions whether it is something that would make sense, would be acceptable or whether this can cause some issues elsewhere.

**Comment by rijswijk** [comment]
The current implementation choice was a deliberate one, to discourage application developers from assuming any ordering in the results from a call to `C_FindObjects`. From prior experience, we know that there are many common mistakes made by application developers that used the PKCS #11 interface.

That said, I see no harm in making this type of functionality available as an optional feature (that can be turned on or off at run-time), so if you would be willing to contribute the code, we would certainly consider the PR for inclusion. 

Does that answer your question?

**Comment by Jakuje** [comment]
Thank you for prompt reply. Yes, it answers my question. I was suspecting that it might be intentional :) I am not fluent in C++ so to contribute code for this, it will take some time, especially if I would need to make it runtime configurable.

I was considering sorting this in application using the pkcs11, but did not come with a sensible solution so far.

**Comment by rijswijk** [comment]
I checked out the C++ specification, and `std::set` is actually iterated in a sorted order, but the set that is being iterated here probably just has pointers to objects (or handles to objects), hence no order based on any attributes is imposed. So in order to achieve your goal, one possible approach could be to provide an alternative `std::set` template instantiation specifying a custom comparison operator (second argument to the template). You'd then need to look at the actual objects and impose whatever order you prefer. Note, though, that this may be a rabbit hole because you'll have to, e.g., deal with objects that don't have a `CKA_ID` attribute set, etc.
